### ISSUE TITLE
question for bounding box

### ISSUE THREAD

**Issue by hqh1997** [chenyixie123/ESCC_ML#4]

**Comment by hqhtiantian520** [comment]
> Dear author, We found some problems in cutting off the maximum ROI area with the provided case. Taking Oeta_40 as an example, 40seg1.nii.gz has only 1 ROI section and the code seems to be fine, but 40seg3.nii.gz has 3 sections and the code does not seem to cut off the largest ROI area . Is it convenient to explain this? Problem code as follows: **def maskcroppingbox(images_array, use2D=False): images_array_2 = np.argwhere(images_array) (zstart, ystart, xstart), (zstop, ystop, xstop) = images_array_2.min(axis=0), images_array_2.max(axis=0) + 1 return (zstart, ystart, xstart), (zstop, ystop, xstop)** roi_images = image_array[zstart-1:zstop+1,ystart:ystop,xstart:xstop].transpose((2,1,0))
